# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "/etc/prometheus/alert.rules"   

scrape_configs:
  - job_name: monitor_server
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: example_server
    scrape_interval: 5s
    static_configs:
      - targets: ['example.com:9080']   
  
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
