# This is a basic workflow to help you get started with Actions
name: Create MI files archive

# Controls when the action will run. 
on:
  # Triggers the workflow on push only for the master branch
  push:
    branches: [ master, monitoring-guide ]
    paths:
      - /_posts/resources/2020-01-29-Monitoring-Prometheus-Loki-Grafana/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'MI.zip'
          directory: './_posts/resources/2020-01-29-Monitoring-Prometheus-Loki-Grafana/'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "MI.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
